# Generated by Django 5.1.15 on 2026-08-31 20:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firms', '0002_userinvitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_number', models.CharField(max_length=50)),
                ('client_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('ORGANISATION', 'Organisation')], default='INDIVIDUAL', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('company_registration_number', models.CharField(blank=True, max_length=100)),
                ('national_id_or_passport', models.CharField(blank=True, max_length=100)),
                ('kra_pin', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clients', to=settings.AUTH_USER_MODEL)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='firms.firm')),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['firm', 'name'], name='clients_client_firm_name_idx'), models.Index(fields=['firm', 'status'], name='clients_client_firm_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('firm', 'client_number'), name='unique_client_number_per_firm')],
            },
        ),
    ]
