# Generated by Django 5.1.15 on 2026-09-03 09:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firms', '0003_firm_accent_color'),
        ('matters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('MENTION', 'Mention'), ('HEARING', 'Hearing'), ('FILING_DEADLINE', 'Filing deadline'), ('CLIENT_MEETING', 'Client meeting'), ('INTERNAL_TASK', 'Internal task'), ('OTHER', 'Other')], max_length=30)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('court_name', models.CharField(blank=True, max_length=180)),
                ('location', models.CharField(blank=True, max_length=180)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('ADJOURNED', 'Adjourned'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_diary_events', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_diary_events', to=settings.AUTH_USER_MODEL)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_events', to='firms.firm')),
                ('matter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diary_events', to='matters.matter')),
            ],
            options={
                'ordering': ('start_at', 'title'),
            },
        ),
        migrations.CreateModel(
            name='DiaryReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remind_at', models.DateTimeField()),
                ('channel', models.CharField(choices=[('IN_APP', 'In app'), ('EMAIL', 'Email')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='diary.diaryevent')),
            ],
            options={
                'ordering': ('remind_at', 'channel'),
            },
        ),
        migrations.AddIndex(
            model_name='diaryevent',
            index=models.Index(fields=['firm', 'start_at'], name='diary_event_firm_start_idx'),
        ),
        migrations.AddIndex(
            model_name='diaryevent',
            index=models.Index(fields=['firm', 'status'], name='diary_event_firm_status_idx'),
        ),
        migrations.AddIndex(
            model_name='diaryevent',
            index=models.Index(fields=['firm', 'event_type'], name='diary_event_firm_type_idx'),
        ),
        migrations.AddIndex(
            model_name='diaryevent',
            index=models.Index(fields=['assigned_to', 'start_at'], name='diary_event_assigned_idx'),
        ),
        migrations.AddIndex(
            model_name='diaryreminder',
            index=models.Index(fields=['status', 'remind_at'], name='diary_rem_status_due_idx'),
        ),
        migrations.AddIndex(
            model_name='diaryreminder',
            index=models.Index(fields=['channel', 'status'], name='diary_rem_channel_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='diaryreminder',
            constraint=models.UniqueConstraint(fields=('event', 'remind_at', 'channel'), name='unique_diary_reminder_schedule'),
        ),
    ]
