# Generated by Django 5.1.15 on 2026-08-31 21:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firms', '0002_userinvitation'),
        ('matters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_locations', to='firms.firm')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='physical_files.storagelocation')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PhysicalFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('physical_file_number', models.CharField(max_length=80)),
                ('volume_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('IN_STORAGE', 'In storage'), ('CHECKED_OUT', 'Checked out'), ('ARCHIVED', 'Archived'), ('MISSING', 'Missing'), ('DESTROYED', 'Destroyed')], default='IN_STORAGE', max_length=20)),
                ('digitisation_status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('PREPARING', 'Preparing'), ('SCANNING', 'Scanning'), ('INDEXING', 'Indexing'), ('QUALITY_REVIEW', 'Quality review'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On hold')], default='NOT_STARTED', max_length=20)),
                ('barcode_or_qr_code', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_files', to='firms.firm')),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='physical_files', to='matters.matter')),
                ('storage_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='physical_files', to='physical_files.storagelocation')),
            ],
            options={
                'ordering': ('physical_file_number', 'volume_number'),
            },
        ),
        migrations.CreateModel(
            name='FileCheckout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checked_out_to_name', models.CharField(blank=True, max_length=255)),
                ('checked_out_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expected_return_at', models.DateTimeField(blank=True, null=True)),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('checked_out_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_checkouts_created', to=settings.AUTH_USER_MODEL)),
                ('checked_out_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_checkouts_received', to=settings.AUTH_USER_MODEL)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_checkouts', to='firms.firm')),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_returns_created', to=settings.AUTH_USER_MODEL)),
                ('physical_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='physical_files.physicalfile')),
            ],
            options={
                'ordering': ('-checked_out_at',),
                'indexes': [models.Index(fields=['firm', 'returned_at'], name='phys_checkout_firm_return_idx'), models.Index(fields=['physical_file', 'returned_at'], name='phys_checkout_file_return_idx'), models.Index(fields=['expected_return_at'], name='phys_checkout_expected_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='storagelocation',
            index=models.Index(fields=['firm', 'name'], name='phys_loc_firm_name_idx'),
        ),
        migrations.AddIndex(
            model_name='storagelocation',
            index=models.Index(fields=['firm', 'parent'], name='phys_loc_firm_parent_idx'),
        ),
        migrations.AddConstraint(
            model_name='storagelocation',
            constraint=models.UniqueConstraint(fields=('firm', 'parent', 'name'), name='unique_storage_location_sibling'),
        ),
        migrations.AddIndex(
            model_name='physicalfile',
            index=models.Index(fields=['firm', 'physical_file_number'], name='phys_file_firm_number_idx'),
        ),
        migrations.AddIndex(
            model_name='physicalfile',
            index=models.Index(fields=['firm', 'status'], name='phys_file_firm_status_idx'),
        ),
        migrations.AddIndex(
            model_name='physicalfile',
            index=models.Index(fields=['firm', 'digitisation_status'], name='phys_file_firm_digit_idx'),
        ),
        migrations.AddConstraint(
            model_name='physicalfile',
            constraint=models.UniqueConstraint(fields=('firm', 'physical_file_number', 'volume_number'), name='unique_physical_file_volume_per_firm'),
        ),
    ]
