# Generated by Django 5.1.15 on 2026-08-31 21:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firms', '0002_userinvitation'),
        ('physical_files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitisationReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scan_date', models.DateField(blank=True, null=True)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('missing_page_flag', models.BooleanField(default=False)),
                ('poor_quality_flag', models.BooleanField(default=False)),
                ('rescan_required', models.BooleanField(default=False)),
                ('completion_confirmed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digitisation_reviews', to='firms.firm')),
                ('physical_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digitisation_reviews', to='physical_files.physicalfile')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='digitisation_reviews', to=settings.AUTH_USER_MODEL)),
                ('scanner_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='digitisation_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['firm', 'completion_confirmed'], name='digit_review_firm_done_idx'), models.Index(fields=['physical_file', 'created_at'], name='digit_review_file_created_idx')],
            },
        ),
    ]
