# Generated by Django 5.1.15 on 2026-09-01 17:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firms', '0002_userinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='accent_color',
            field=models.CharField(default='#0f766e', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color, for example #0f766e.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
    ]
