# Generated by Django 5.1.15 on 2026-08-31 20:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('firms', '0002_userinvitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_areas', to='firms.firm')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Matter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matter_number', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACTIVE', 'Active'), ('ON_HOLD', 'On hold'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived')], default='OPEN', max_length=20)),
                ('opened_date', models.DateField(default=django.utils.timezone.localdate)),
                ('closed_date', models.DateField(blank=True, null=True)),
                ('physical_file_exists', models.BooleanField(default=False)),
                ('confidentiality_level', models.CharField(choices=[('STANDARD', 'Standard'), ('RESTRICTED', 'Restricted'), ('PARTNER_ONLY', 'Partner only'), ('CUSTOM', 'Custom')], default='STANDARD', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matters', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_matters', to=settings.AUTH_USER_MODEL)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matters', to='firms.firm')),
                ('responsible_advocate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advocate_matters', to=settings.AUTH_USER_MODEL)),
                ('responsible_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_matters', to=settings.AUTH_USER_MODEL)),
                ('practice_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matters', to='matters.practicearea')),
            ],
            options={
                'ordering': ('-opened_date', 'matter_number'),
            },
        ),
        migrations.CreateModel(
            name='MatterParty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('party_type', models.CharField(choices=[('CLIENT', 'Client'), ('OPPOSING_PARTY', 'Opposing party'), ('INTERESTED_PARTY', 'Interested party'), ('WITNESS', 'Witness'), ('COMPANY_DIRECTOR', 'Company director'), ('OTHER', 'Other')], max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matter_parties', to='firms.firm')),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='matters.matter')),
            ],
            options={
                'ordering': ('party_type', 'name'),
                'indexes': [models.Index(fields=['firm', 'name'], name='matters_party_firm_name_idx'), models.Index(fields=['firm', 'party_type'], name='matters_party_firm_type_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='practicearea',
            constraint=models.UniqueConstraint(fields=('firm', 'name'), name='unique_practice_area_name_per_firm'),
        ),
        migrations.AddConstraint(
            model_name='practicearea',
            constraint=models.UniqueConstraint(fields=('firm', 'code'), name='unique_practice_area_code_per_firm'),
        ),
        migrations.AddIndex(
            model_name='matter',
            index=models.Index(fields=['firm', 'matter_number'], name='matters_matter_firm_number_idx'),
        ),
        migrations.AddIndex(
            model_name='matter',
            index=models.Index(fields=['firm', 'status'], name='matters_matter_firm_status_idx'),
        ),
        migrations.AddIndex(
            model_name='matter',
            index=models.Index(fields=['firm', 'title'], name='matters_matter_firm_title_idx'),
        ),
        migrations.AddConstraint(
            model_name='matter',
            constraint=models.UniqueConstraint(fields=('firm', 'matter_number'), name='unique_matter_number_per_firm'),
        ),
    ]
