# Generated by Django 5.1.15 on 2026-09-06 16:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_deleted_at_client_clients_client_firm_del_idx'),
        ('firms', '0003_firm_accent_color'),
        ('matters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='matter',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='matter',
            index=models.Index(fields=['firm', 'deleted_at'], name='matters_matter_firm_del_idx'),
        ),
    ]
